#!/usr/bin/env bash
# Script to configure Nginx to redirect /redirect_me to another page with a 301 Moved Permanently status.

# Update package list and install Nginx
apt-get update
apt-get -y install nginx

# Allowing Nginx HTTP through the firewall
sudo ufw allow 'Nginx HTTP'

# Create directory for the content
sudo mkdir -p /var/www/html/

# Set permissions for the content
sudo chmod -R 755 /var/www

# Create the basic index.html page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom server configuration with redirection
SERVER_CONFIGURATION="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

# Set the Nginx server configuration
echo "$SERVER_CONFIGURATION" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
