#!/usr/bin/env bash
# Script to create a custom 404 page that contains the string Ceci n'est pas une page.

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Allowing Nginx HTTP through the firewall
# sudo ufw allow 'Nginx HTTP'

# Configuring Nginx usage of a custom 404 page
echo "error_page 404 /404.html;" >> /etc/nginx/sites-available/default

# Create a custom 404 page
echo "<html><body>Ceci n'est pas une page</body></html>" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
# sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
# sudo sed -i '/error_page 404/a location = /custom_404.html {\n\tinternal;\n}' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo nginx -t && sudo service nginx restart
