#!/usr/bin/env bash

# shellcheck disable=SC2154

# Installs nginx on my server
sudo apt-get update
sudo apt-get install -y nginx || { echo "Failed to install Nginx. Exiting."; exit 1; }

# Create directories and files
sudo mkdir -p /var/www/test/html
echo "Hello World!" | sudo tee /var/www/test/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/test/html/404.html > /dev/null

# Configure Nginx
cat <<EOF | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
    listen      80;
    listen      [::]:80;
    add_header  X-Served-By "\$HOSTNAME";
    root        /var/www/test/html;
    index       index.html index.htm;

    location /redirect_me {
        return 301 'https://www.youtube.com/watch?v=QH2-TGUlwu4';
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/test/html;
        internal;
    }
}
EOF

# Check Nginx configuration and restart Nginx service if configuration is valid
if sudo nginx -t; then
    sudo systemctl restart nginx
else
    echo "Nginx configuration test failed. Please check configuration."
    exit 1
fi
