#!/usr/bin/env bash

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null
    if ! command -v "$1" &> /dev/null; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}
install nginx # Install nginx if not already installed

echo -e "\nSetting up some minor stuff.\n"

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create directories if not present
for dir in /var/www/test/html /var/www/test/error; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Creating new index and error page
echo "Hello World!" > /var/www/test/html/index.html
echo "Ceci n'est pas une page" > /var/www/test/html/404.html

# Backup default server config file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup

server_config="server {
    listen      80;
    listen      [::]:80;
    root        /var/www/test/html;
    index       index.html index.htm;
    server_name _;
    add_header  X-Served-By \$hostname;

    location /redirect_me {
        return 301 'https://www.youtube.com/watch?v=QH2-TGUlwu4';
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/test/html;
        internal;
    }
}"

echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-available/default

# Enable the configuration if it's not already linked
if [ ! -L /etc/nginx/sites-enabled/default ]; then
    sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
fi

# Check if Nginx is running and start or restart it accordingly
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo systemctl start nginx
else
    sudo systemctl restart nginx
fi
