#!/usr/bin/env bash
# Fixes for Nginx to ensure it's running and listening on port 80

sudo rm /etc/nginx/sites-enabled/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
