#!/usr/bin/env bash
# Manages daemons
#     When passing the argument start:
#         Starts manage_my_process
#         Creates a file containing its PID in /var/run/my_process.pid
#         Displays manage_my_process started
#     When passing the argument stop:
#         Stops manage_my_process
#         Deletes the file /var/run/my_process.pid
#         Displays manage_my_process stopped
#     When passing the argument restart
#         Stops manage_my_process
#         Deletes the file /var/run/my_process.pid
#         Starts manage_my_process
#         Creates a file containing its PID in /var/run/my_process.pid
#         Displays manage_my_process restarted
#     Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

start_process() {
    if [ -f "/var/run/my_process.pid" ]; then
        echo "manage_my_process is already running."
    else
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        touch /tmp/my_process
        echo "manage_my_process started."
        while true; do
            echo "I am alive!" >> /tmp/my_process
            sleep 2
        done &
        echo $! >> /var/run/my_process.pid
    fi
}

stop_process() {
    if [ -f "/var/run/my_process.pid" ]; then
        echo "manage_my_process stopped."
        while read -r pid; do
            kill "$pid"
        done < /var/run/my_process.pid
        rm /var/run/my_process.pid
        rm /tmp/my_process
    else
        echo "manage_my_process is not running."
    fi
}

restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted."
}

if [ "$1" == "start" ]; then
    start_process
elif [ "$1" == "stop" ]; then
    stop_process
elif [ "$1" == "restart" ]; then
    restart_process
else
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
fi
