#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

for file in *; do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
