#!/usr/bin/env bash
# Start Apache in a Docker container.

# Update package list
apt-get update

# Install Apache2 if it's not already installed
apt-get install -y apache2

# Start Apache2
service apache2 start
