#!/bin/bash

# Generate an RSA key pair with the following requirements:
# - Name of the created private key: school
# - Number of bits: 4096
# - Passphrase: betty

# Generating the RSA key pair
ssh-keygen -b 4096 -f school -N betty
